server:
  port: 8090

spring:
  application:
    name: kz-file-parser
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 300000
app:
  rabbit:
    queue: csv-lines
    exchange: csv-lines-exchange
    routing-key: csv.lines
    tariffs:
      queue: tariffs-lines
      exchange: tariffs-lines-exchange
      routing-key: tariffs.lines
  analytics:
    base-url: http://localhost:8080
  jwtSecret: ${AUTH_KEY:sOBNXOci4tCpIUA2uIKKnRADVGu/hFaLpBP5tC93Wf1nAueXF1VPBgF+5otQzWA580BvPlphiMSsIsKQnFnhrQ==}
  jwtExpirationMs: ${AUTH_KEY_EXPIRATION_MS:86400000}
