server:
  port: 8080

spring:
  application:
    name: kz-file-parser
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

app:
  rabbit:
    queue: csv-lines
    exchange: csv-lines-exchange
    routing-key: csv.lines
  jwtSecret: ${AUTH_KEY:sOBNXOci4tCpIUA2uIKKnRADVGu/hFaLpBP5tC93Wf1nAueXF1VPBgF+5otQzWA580BvPlphiMSsIsKQnFnhrQ==}
  jwtExpirationMs: ${AUTH_KEY_EXPIRATION_MS:86400000}
